version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo not installing anything else
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo build env `env` `$env`
      - echo Compiling the Node.js code
      - npm run build:ci
      - npm run export
artifacts:
  files:
    - '**/*'
  base-directory: out